language: go
go:
  - 1.9.2
before_cache:
  - ccache -s
env:
  global:
    - USE_CCACHE=1
cache:
  directories:
    - $HOME/.ccache
install:
  - mkdir -p $HOME/.ccache
  - export PATH=/usr/lib/ccache:$PATH
  - ./tools/build.py
script:
  - ./tools/test.sh
